version: '3'

services: 
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  redis:
    image: redis
  api:
    build: 
      context: .
    command: bash -c "sqlx migrate run && cargo test"
    volumes:
      - ../..:/app
      - ./.env:/app/.env
      - /tmp/.cargo/target:/tmp/target
      - ~/.cargo/registry:/root/.cargo/registry
